name: Automated tests

on:
  workflow_dispatch:
    inputs:
      APIName:
        description: APIusername
        required: true
      APIPassword:
        description: APIpassword
        required: true
      UIName:
        description: UIusername
        required: true
      UIPassword:
        description: UIpassword
        required: true
      deployment_target:
        description: Choose target
        required: true
        default: all
        type: choice
        options:
          - all
          - ui
          - api

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - run: ls
      - run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/Grigory98/AutomationTestsFramework/actions/artifacts?name=allure-results" 
          | jq -r '.artifacts[0].id') 
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/Grigory98/AutomationTestsFramework/actions/artifacts/$ARTIFACT_ID/zip 
          -o artifacts.zip &&
          REPORT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/Grigory98/AutomationTestsFramework/actions/artifacts?name=github-pages" 
          | jq -r '.artifacts[0].id')
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/Grigory98/AutomationTestsFramework/actions/artifacts/$REPORT_ID/zip 
          -o pages.zip
      - run: ls
      - run: mkdir allure-results
      - run: mkdir old_pages pages_history
      - name: Store allure history
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  run-tests-ui:
    needs: download-history
    if: "github.event.inputs.deployment_target == 'ui' || github.event.inputs.deployment_target == 'all'"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip
      - name: Maven clean install
        run: mvn clean install -Dmaven.test.skip
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Run UI tests
        run: mvn test -pl ui
          -Duiusername="${{ github.event.inputs.UIName }}"
          -Duipassword="${{ github.event.inputs.UIPassword }}"
        continue-on-error: true
      - name: Save allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-ui
          path:
            allure-results
          retention-days: 1

  run-tests-api:
    needs: download-history
    if: "github.event.inputs.deployment_target == 'api' || github.event.inputs.deployment_target == 'all'"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip
      - name: Maven clean install
        run: mvn clean install -Dmaven.test.skip
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Run API tests
        run: mvn test -pl api
          -Dapiusername="${{ github.event.inputs.APIName }}"
          -Dapipassword="${{ github.event.inputs.APIPassword }}"
        continue-on-error: true
      - name: Save allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: [run-tests-ui, run-tests-api]
    if: always()
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.tgz
          && sudo tar -zxvf allure-2.23.0.tgz -C /opt/
          && sudo ln -s /opt/allure-2.23.0/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: allure generate -c allure-results -o _site
      - name: Save generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    if: always()
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9