name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Chooose target
        required: true
        default:
          type: choice
          options:
            - all
            - ui
            - api

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Build with Maven and Run UI tests
        if: "github.event.inputs.deployment_target == 'ui'"
        run: mvn -B package --file pom.xml
      - name: Build with Maven and Run API tests
        if: "github.event.inputs.deployment_target == 'api'"
        run: mvn -B package --file pom.xml
      - name: Build with Maven and Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: mvn -B package --file pom.xml