name: Automated tests

on:
  workflow_dispatch:
    inputs:
      APIName:
        description: APIusername
        required: true
      APIPassword:
        description: APIpassword
        required: true
      UIName:
        description: UIusername
        required: true
      UIPassword:
        description: UIpassword
        required: true
      deployment_target:
        description: Choose target
        required: true
        default: all
        type: choice
        options:
          - all
          - ui
          - api

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip
      - name: Maven clean install
        run: mvn clean install -Dmaven.test.skip
      - name: Run UI tests
        if: "github.event.inputs.deployment_target == 'ui'"
        run: mvn test -pl ui -Duiusername="${{ github.event.inputs.UIName }}" -Duipassword="${{ github.event.inputs.UIPassword }}"
      - name: Run API tests
        if: "github.event.inputs.deployment_target == 'api'"
        run: mvn test -pl api -Dapiusername="${{ github.event.inputs.APIName }}" -Dapipassword="${{ github.event.inputs.APIPassword }}"
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: mvn test -Duiusername="${{ github.event.inputs.UIName }}" -Duipassword="${{ github.event.inputs.UIPassword }}" -Dapiusername="${{ github.event.inputs.APIName }}" -Dapipassword="${{ github.event.inputs.APIPassword }}"